function getCardapio() {
  return [
    {
      id: 1,
      name: "Coxinha de Frango",
      image: "./images/novas-imgs/coxinha-sm.jpg",
      price: 58.0,
      desc: "Coxinha recheada com frango",
      congelado: 0,
      priceCongelado: 0,
    },
    {
      id: 2,
      name: "Bolinha de Queijo Tradicional",
      image: "./images/novas-imgs/bolinha-de-queijo-sm.jpg",
      price: 58.0,
      desc: "Bolinha frita recheada com queijo mussarela",
      congelado: 0,
      priceCongelado: 0,
    },
    {
      id: 3,
      name: "Bolinha de Queijo c/ Alho Frito",
      image: "./images/novas-imgs/bolinha-de-queijo-sm.jpg",
      price: 58.0,
      desc: "Bolinha recheada com queijo mussarela e alho frito",
      congelado: 0,
      priceCongelado: 0,
    },
    {
      id: 4,
      name: "Maravilha",
      image: "./images/novas-imgs/maravilha-sm.jpg",
      price: 58.0,
      desc: "Maravilha recheada com presunto e queijo mussarela",
      congelado: 0,
      priceCongelado: 0,
    },
    {
      id: 5,
      name: "Risoles de Carne",
      image: "./images/novas-imgs/risoles-carne-sm.jpg",
      price: 58.0,
      desc: "Risoles recheada com carne bovina",
      congelado: 0,
      priceCongelado: 0,
    },
    {
      id: 6,
      name: "Risoles de Carne c/ Queijo",
      image: "./images/novas-imgs/risoles-carne-sm.jpg",
      price: 58.0,
      desc: "Risoles recheado com carne bovina e queijo mussarela",
      congelado: 0,
      priceCongelado: 0,
    },
    {
      id: 7,
      name: "Risoles de Calabresa",
      image: "./images/novas-imgs/risoles-calabresa-sm.png",
      price: 58.0,
      desc: "Risoles recheado com calabresa",
      congelado: 0,
      priceCongelado: 0,
    },
    {
      id: 8,
      name: "Risoles de Calabresa c/ Queijo",
      image: "./images/novas-imgs/risoles-calabresa-sm.png",
      price: 58.0,
      desc: "Risoles recheado com calabresa e queijo mussarela",
      congelado: 0,
      priceCongelado: 0,
    },
    {
      id: 9,
      name: "Croquete de Carne",
      image: "./images/novas-imgs/croquete-carne-sm.jpg",
      price: 58.0,
      desc: "Croquete de carne bovina",
      congelado: 0,
      priceCongelado: 0,
    },
    {
      id: 10,
      name: "Croquete de Frango",
      image: "./images/novas-imgs/croquete-frango-sm.png",
      price: 58.0,
      desc: "Croquete de frango",
      congelado: 0,
      priceCongelado: 0,
    },
  ];
}
